language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm test
  - npm run coverage

notifications:
  email:
    recipients:
      - nathanfrancy@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
